# Generated by Django 3.2 on 2021-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='emprestado',
            field=models.BooleanField(),
        ),
    ]
