# Generated by Django 3.2 on 2021-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, upload_to='capas/%d/%m/%Y'),
        ),
    ]
